backend:
  name: github
  repo: thewhiteh4t/thewhiteh4t.github.io

publish_mode: editorial_workflow
media_folder: images/posts

collections:
  - name: 'post'
    label: 'Post'
    folder: '_posts'
    extension: 'html'
    sort: 'date:asce'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - label: 'Title'
        name: 'title'
        widget: 'string'
      
      - label: 'Description'
        name: 'desc'
        widget: 'string'
      
      - label: 'Layout'
        name: 'layout'
        default: 'post'
        widget: 'hidden'

      - label: 'Publish Date and Time'
        name: 'date'
        widget: 'datetime'
        default: ''
        dateFormat: 'DD.MM.YYYY' # e.g. 24.12.2021
        timeFormat: 'HH:mm' # e.g. 21:07
        format: 'LLL'
        pickerUtc: false
      
      - label: 'Card Image'
        name: 'image'
        widget: 'image'
        required: false
        tagname: ''

      - label: 'Body'
        name: 'body'
        widget: 'markdown'
        required: true

